"use client";
import{useEffect,useState}from"react";import{useParams}from"next/navigation";import Flag from"@/components/features/Flag";import{formatDate,formatMoney}from"@/lib/money";import{finishReconciliation,getCurrentReconciliation,importQIF,setReconciliationSelection,startReconciliation,type Reconciliation}from"@/lib/bankReconciliation";
export default function ReconcilePage(){const bankId=Number(useParams().id);const[row,setRow]=useState<Reconciliation|null>(null),[statementDate,setStatementDate]=useState(""),[ending,setEnding]=useState(""),[error,setError]=useState(""),[info,setInfo]=useState("");useEffect(()=>{getCurrentReconciliation(bankId).then(setRow).catch(()=>{})},[bankId]);
async function start(){try{setError("");setRow(await startReconciliation(bankId,{statement_date:statementDate,ending_statement_balance:ending}))}catch(e){setError(e instanceof Error?e.message:"Could not start reconciliation")}}
async function toggle(id:number){if(!row)return;const ids=row.items.filter(x=>x.cleared).map(x=>x.id);const next=ids.includes(id)?ids.filter(x=>x!==id):[...ids,id];try{setRow(await setReconciliationSelection(bankId,row.id,next))}catch(e){setError(e instanceof Error?e.message:"Could not update selection")}}
async function qif(file:File){if(!row)return;try{const res=await importQIF(bankId,row.id,await file.text());setRow(res.reconciliation);setInfo(`Imported ${res.imported}; matched ${res.matched}.`)}catch(e){setError(e instanceof Error?e.message:"QIF import failed")}}
async function finish(){if(!row)return;try{setRow(await finishReconciliation(bankId,row.id));setInfo("Reconciliation finished.")}catch(e){setError(e instanceof Error?e.message:"Could not finish reconciliation")}}
if(!row)return <div className="p-6 max-w-xl"><h1 className="text-xl font-semibold mb-1">Bank Reconciliation</h1><p className="text-sm text-slate-500 mb-5">Start with your statement date and ending balance.</p>{error&&<p className="text-red-600 mb-3">{error}</p>}<label className="block text-sm mb-3">Statement Date<input className="block border rounded p-2 w-full" type="date" value={statementDate} onChange={e=>setStatementDate(e.target.value)}/></label><label className="block text-sm mb-4">Ending Statement Balance<input className="block border rounded p-2 w-full" type="number" step="0.01" value={ending} onChange={e=>setEnding(e.target.value)}/></label><button className="bg-blue-600 text-white rounded px-4 py-2" onClick={()=>void start()}>Start Reconciliation</button></div>;
return <div className="p-6 max-w-6xl"><div className="flex justify-between gap-4"><div><h1 className="text-xl font-semibold">Bank Reconciliation</h1><p className="text-sm text-slate-500">{row.bank_account_name} · statement {formatDate(row.statement_date)}</p></div><Flag name="release.accounting.bank_reconciliation.qif"><label className="border rounded px-3 py-2 text-sm cursor-pointer">QIF Import<input className="hidden" type="file" accept=".qif,text/plain" onChange={e=>e.target.files?.[0]&&void qif(e.target.files[0])}/></label></Flag></div>{error&&<p className="text-red-600 mt-3">{error}</p>}{info&&<p className="text-green-700 mt-3">{info}</p>}<div className="grid grid-cols-4 gap-3 my-5 text-sm"><div className="border rounded p-3">Beginning<br/><b>{formatMoney(row.beginning_balance)}</b></div><div className="border rounded p-3">Cleared<br/><b>{formatMoney(row.cleared_balance)}</b></div><div className="border rounded p-3">Statement<br/><b>{formatMoney(row.ending_statement_balance)}</b></div><div className={`border rounded p-3 ${row.balanced?"bg-green-50":"bg-amber-50"}`}>Difference<br/><b>{formatMoney(row.difference)}</b></div></div><div className="border rounded bg-white overflow-hidden"><table className="w-full text-sm"><thead className="bg-slate-50"><tr><th className="p-3"></th><th className="p-3 text-left">Date</th><th className="p-3 text-left">Type</th><th className="p-3 text-left">Reference</th><th className="p-3 text-left">Description</th><th className="p-3 text-right">Amount</th></tr></thead><tbody>{row.items.map(x=><tr key={x.id} className="border-t"><td className="p-3"><input disabled={row.status!=="OPEN"} type="checkbox" checked={x.cleared} onChange={()=>void toggle(x.id)}/></td><td className="p-3">{formatDate(x.transaction_date)}</td><td className="p-3">{x.source_type}</td><td className="p-3">{x.reference_number||"—"}</td><td className="p-3">{x.description||"—"}</td><td className="p-3 text-right">{formatMoney(x.signed_amount)}</td></tr>)}</tbody></table></div>{row.status==="OPEN"&&<div className="flex justify-end mt-4"><button disabled={!row.balanced} className="bg-blue-600 text-white rounded px-4 py-2 disabled:opacity-40" onClick={()=>void finish()}>Finish Reconciliation</button></div>}</div>}
