"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {useParams} from "next/navigation";
import {getCheckSetup,updateCheckSetup,type BankCheckSetup} from "@/lib/checkSetup";
export default function CheckSetupPage(){const bankId=Number(useParams().id);const[setup,setSetup]=useState<BankCheckSetup|null>(null),[nextNumber,setNextNumber]=useState("1"),[prefix,setPrefix]=useState(""),[position,setPosition]=useState<"TOP"|"MIDDLE"|"BOTTOM">("TOP"),[memoLine,setMemoLine]=useState(true),[signatureLine,setSignatureLine]=useState(true),[error,setError]=useState(""),[saved,setSaved]=useState(""),[saving,setSaving]=useState(false);
useEffect(()=>{getCheckSetup(bankId).then(row=>{setSetup(row);setNextNumber(String(row.next_check_number));setPrefix(row.check_number_prefix||"");setPosition(row.check_stock_position);setMemoLine(row.memo_line_enabled);setSignatureLine(row.signature_line_enabled)}).catch(err=>setError(err instanceof Error?err.message:"Could not load Check Setup"))},[bankId]);
async function save(){const parsed=Number(nextNumber);if(!Number.isInteger(parsed)||parsed<1){setError("Next check number must be a positive whole number.");return}setSaving(true);setError("");setSaved("");try{const row=await updateCheckSetup(bankId,{next_check_number:parsed,check_number_prefix:prefix.trim()||null,check_stock_position:position,memo_line_enabled:memoLine,signature_line_enabled:signatureLine});setSetup(row);setSaved("Check setup saved.")}catch(err){setError(err instanceof Error?err.message:"Could not save Check Setup")}finally{setSaving(false)}}
if(!setup&&!error)return <div className="p-6 text-slate-500">Loading…</div>;
return <div className="max-w-2xl p-6"><Link href="/dashboard/accounting/bank-accounts" className="text-sm text-slate-500 hover:text-slate-900">← Back to Bank Accounts</Link><h1 className="text-2xl font-bold text-slate-900 mt-4">Check Setup</h1><p className="text-sm text-slate-500 mt-1">{setup?.bank_account_name||"Bank account"} · configure automatic numbering and check stock.</p>{error&&<div className="mt-4 rounded border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}{saved&&<div className="mt-4 rounded border border-green-200 bg-green-50 p-3 text-sm text-green-700">{saved}</div>}{setup&&<div className="mt-6 space-y-5 rounded-xl border border-slate-200 bg-white p-6"><div className="grid grid-cols-2 gap-4"><label className="text-sm text-slate-700">Next Check Number<input className="mt-1 w-full rounded border border-slate-300 px-3 py-2" type="number" min="1" step="1" value={nextNumber} onChange={e=>setNextNumber(e.target.value)}/></label><label className="text-sm text-slate-700">Optional Prefix<input className="mt-1 w-full rounded border border-slate-300 px-3 py-2" maxLength={20} value={prefix} onChange={e=>setPrefix(e.target.value)} placeholder="e.g. A-"/></label></div><label className="block text-sm text-slate-700">Check Stock Position<select className="mt-1 w-full rounded border border-slate-300 px-3 py-2" value={position} onChange={e=>setPosition(e.target.value as "TOP"|"MIDDLE"|"BOTTOM")}><option value="TOP">Check on top</option><option value="MIDDLE">Check in middle</option><option value="BOTTOM">Check on bottom</option></select></label><label className="flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" checked={memoLine} onChange={e=>setMemoLine(e.target.checked)}/>Print memo line</label><label className="flex items-center gap-3 text-sm text-slate-700"><input type="checkbox" checked={signatureLine} onChange={e=>setSignatureLine(e.target.checked)}/>Print signature line</label><p className="text-xs text-slate-500">When Write Checks leaves the check number blank, the next configured number is reserved and advanced automatically.</p><button onClick={()=>void save()} disabled={saving} className="rounded bg-slate-900 px-4 py-2 text-sm font-medium text-white disabled:opacity-50">{saving?"Saving…":"Save Check Setup"}</button></div>}</div>}
