"use client";
import { useEffect, useState } from "react";
import Link from "next/link";
import { downloadAuditCsv, listAuditEvents, type AuditCenterItem } from "@/lib/auditCenter";

export default function AuditingCenterPage(){
  const [items,setItems]=useState<AuditCenterItem[]>([]),[total,setTotal]=useState(0);
  const [entityType,setEntityType]=useState(""),[action,setAction]=useState(""),[search,setSearch]=useState(""),[dateFrom,setDateFrom]=useState(""),[dateTo,setDateTo]=useState("");
  const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const filters=()=>({entity_type:entityType||undefined,action:action||undefined,search:search||undefined,date_from:dateFrom?`${dateFrom}T00:00:00`:undefined,date_to:dateTo?`${dateTo}T23:59:59`:undefined});
  async function load(){setLoading(true);setError("");try{const r=await listAuditEvents({...filters(),limit:200,offset:0});setItems(r.items);setTotal(r.total);}catch(e){setError(e instanceof Error?e.message:"Could not load audit activity.");}finally{setLoading(false);}}
  useEffect(()=>{void load();/* eslint-disable-next-line react-hooks/exhaustive-deps */},[]);
  async function exportCsv(){setBusy(true);setError("");try{await downloadAuditCsv(filters());}catch(e){setError(e instanceof Error?e.message:"Could not export audit activity.");}finally{setBusy(false);}}
  return <div className="max-w-7xl mx-auto p-6 space-y-6">
    <div className="flex items-start justify-between gap-4"><div><Link href="/dashboard/settings/permissions" className="text-sm text-slate-500 hover:text-slate-800">← Back to settings</Link><h1 className="text-2xl font-semibold text-slate-900 mt-2">Auditing Center</h1><p className="text-sm text-slate-500 mt-1">Read-only organization activity from the immutable audit log.</p></div><button onClick={exportCsv} disabled={busy} className="px-4 py-2 rounded-md bg-slate-900 text-white text-sm disabled:opacity-50">{busy?"Exporting…":"Export CSV"}</button></div>
    <form onSubmit={e=>{e.preventDefault();void load();}} className="grid gap-3 md:grid-cols-6 rounded-lg border border-slate-200 bg-white p-4">
      <input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search changes" className="border rounded-md px-3 py-2 text-sm md:col-span-2"/><input value={entityType} onChange={e=>setEntityType(e.target.value)} placeholder="Entity type" className="border rounded-md px-3 py-2 text-sm"/><input value={action} onChange={e=>setAction(e.target.value)} placeholder="Action" className="border rounded-md px-3 py-2 text-sm"/><input type="date" value={dateFrom} onChange={e=>setDateFrom(e.target.value)} className="border rounded-md px-3 py-2 text-sm"/><input type="date" value={dateTo} onChange={e=>setDateTo(e.target.value)} className="border rounded-md px-3 py-2 text-sm"/><div className="md:col-span-6 flex items-center gap-3"><button className="px-4 py-2 rounded-md bg-blue-600 text-white text-sm">Apply filters</button><span className="text-sm text-slate-500">{total} matching events</span></div>
    </form>
    {error&&<div className="rounded-md border border-red-200 bg-red-50 p-3 text-sm text-red-700">{error}</div>}
    <div className="rounded-lg border border-slate-200 bg-white overflow-x-auto">{loading?<div className="p-6 text-sm text-slate-500">Loading audit activity…</div>:items.length===0?<div className="p-6 text-sm text-slate-500">No audit activity matches these filters.</div>:<table className="min-w-full text-sm"><thead className="bg-slate-50 text-slate-600"><tr><th className="text-left px-4 py-3">When</th><th className="text-left px-4 py-3">Actor</th><th className="text-left px-4 py-3">Entity</th><th className="text-left px-4 py-3">Action</th><th className="text-left px-4 py-3">Field</th><th className="text-left px-4 py-3">Change</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(i=><tr key={i.id} className="align-top"><td className="px-4 py-3 whitespace-nowrap">{new Date(i.created_at).toLocaleString()}</td><td className="px-4 py-3"><div className="font-medium">{i.actor_name}</div><div className="text-xs text-slate-500">{i.actor_email||i.actor_type}</div></td><td className="px-4 py-3 whitespace-nowrap">{i.entity_type} #{i.entity_id}</td><td className="px-4 py-3">{i.action}</td><td className="px-4 py-3">{i.field_name||"—"}</td><td className="px-4 py-3 min-w-[260px]"><div className="text-xs text-slate-500 break-words">{i.old_value||"—"}</div><div className="text-xs text-slate-400 my-1">→</div><div className="text-xs break-words">{i.new_value||"—"}</div></td></tr>)}</tbody></table>}</div>
  </div>;
}
