"""Runtime capability metadata mirrored from docs/FEATURE_REGISTRY.md.

Applicability metadata lives here while mutable state remains separated across
platform release gates, billing entitlements, organization feature settings,
role/user permissions, and user preferences.
"""

from __future__ import annotations

SETTINGS_FEATURES_GATE = "release.settings.features"

FEATURE_DEFINITIONS: dict[str, dict[str, object]] = {
    "release.accounting.ach_files": {"label": "ACH File Generation", "entitlement": "ach_payments", "org_configurable": True, "permission": "ACCOUNTING.BANK_ACCOUNTS"},
    "release.accounting.ach_test_file": {"label": "$0 ACH Test File", "entitlement": "ach_payments", "org_configurable": True, "permission": "ACCOUNTING.BANK_ACCOUNTS"},
    "release.accounting.bank_accounts": {"label": "Bank Accounts page", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.BANK_ACCOUNTS"},
    "release.accounting.bank_adjustments": {"label": "Adjustments", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.BANK_ACCOUNTS"},
    "release.accounting.bank_feed": {"label": "Bank Feed", "entitlement": "bank_feeds", "org_configurable": True, "permission": "ACCOUNTING.BANK_ACCOUNTS"},
    "release.accounting.bank_reconciliation": {"label": "Bank Reconciliation", "entitlement": "bank_reconciliation", "org_configurable": True, "permission": "ACCOUNTING.BANK_ACCOUNTS"},
    "release.accounting.bank_reconciliation.qif": {"label": "QIF Import", "entitlement": "bank_reconciliation", "org_configurable": True, "permission": "ACCOUNTING.BANK_ACCOUNTS"},
    "release.accounting.bills": {"label": "Bills list page", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.PAYABLES"},
    "release.accounting.bills.manual_post": {"label": "Manually Post Bills", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.PAYABLES"},
    "release.accounting.bills.recurring": {"label": "Recurring Bills", "entitlement": "recurring_bills", "org_configurable": True, "permission": "ACCOUNTING.PAYABLES"},
    "release.accounting.charges": {"label": "Charges list", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.CHARGES"},
    "release.accounting.charges.bulk_upload": {"label": "Bulk tenant charges upload", "entitlement": "bulk_charges", "org_configurable": True, "permission": "ACCOUNTING.CHARGES"},
    "release.accounting.check_printing": {"label": "Check Printing", "entitlement": "check_writing", "org_configurable": True, "permission": "ACCOUNTING.BANK_ACCOUNTS"},
    "release.accounting.check_setup": {"label": "Check Setup", "entitlement": "check_writing", "org_configurable": True, "permission": "ACCOUNTING.BANK_ACCOUNTS"},
    "release.accounting.deposits": {"label": "Deposits list page", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.DEPOSITS"},
    "release.accounting.deposits.edit": {"label": "Edit Bank Deposit", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.DEPOSITS"},
    "release.accounting.deposits.escrow_refund": {"label": "Escrow refund", "entitlement": "escrow_refunds", "org_configurable": True, "permission": "ACCOUNTING.DEPOSITS"},
    "release.accounting.deposits.print": {"label": "Print Bank Deposit", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.DEPOSITS"},
    "release.accounting.deposits.process_nsf": {"label": "Process NSF from deposit", "entitlement": "nsf_processing", "org_configurable": True, "permission": "ACCOUNTING.DEPOSITS"},
    "release.accounting.diagnostics.refund_negative": {"label": "Refund Negative Diagnostic", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.DIAGNOSTICS"},
    "release.accounting.gl_account_permissions": {"label": "GL Account Permissions", "entitlement": "core", "org_configurable": True, "permission": "SETTINGS.PERMISSIONS"},
    "release.accounting.gl_accounts": {"label": "Chart of Accounts page", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.GL_ACCOUNTS"},
    "release.accounting.gl_accounts.recalculate": {"label": "Recalculate Balances", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.GL_ACCOUNTS"},
    "release.accounting.journal_entries": {"label": "Journal Entries page", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.JOURNAL_ENTRIES"},
    "release.accounting.journal_entries.manual_post": {"label": "Manually Post Journal Entries", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.JOURNAL_ENTRIES"},
    "release.accounting.journal_entries.post_gpr": {"label": "Post GPR", "entitlement": "gpr_posting", "org_configurable": True, "permission": "ACCOUNTING.JOURNAL_ENTRIES"},
    "release.accounting.journal_entries.recurring": {"label": "History / Recurring tabs", "entitlement": "recurring_journal_entries", "org_configurable": True, "permission": "ACCOUNTING.JOURNAL_ENTRIES"},
    "release.accounting.late_fees": {"label": "Charge Late Fees", "entitlement": "late_fees", "org_configurable": True, "permission": "ACCOUNTING.RECEIVABLES"},
    "release.accounting.management_fees": {"label": "Management Fee runs list", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.MANAGEMENT_FEES"},
    "release.accounting.management_fees.exclusions": {"label": "Management Fee Exclusions", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.MANAGEMENT_FEES"},
    "release.accounting.management_fees.overcollection": {"label": "Overcollection strategy", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.MANAGEMENT_FEES"},
    "release.accounting.management_fees.post_gpr": {"label": "Post GPR", "entitlement": "gpr_posting", "org_configurable": True, "permission": "ACCOUNTING.MANAGEMENT_FEES"},
    "release.accounting.owner_ach_setup": {"label": "Owner ACH Setup", "entitlement": "ach_payments", "org_configurable": True, "permission": "PEOPLE.OWNERS"},
    "release.accounting.owner_held_security_deposits": {"label": "Owner Held Security Deposits", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.GL_ACCOUNTS"},
    "release.accounting.owner_draw": {"label": "Owner Draw", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.PAYABLES"},
    "release.accounting.owner_statements": {"label": "Statements list", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.OWNER_STATEMENTS"},
    "release.accounting.owner_statements.cash_summary": {"label": "Property Cash Summary", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.OWNER_STATEMENTS"},
    "release.accounting.pay_owners": {"label": "Pay Owners", "entitlement": "owner_payouts", "org_configurable": True, "permission": "ACCOUNTING.MANAGEMENT_FEES"},
    "release.accounting.receipts": {"label": "Receipts list page", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.RECEIVABLES"},
    "release.accounting.receipts.application_fee": {"label": "Application Fee mode/tab", "entitlement": "application_fees", "org_configurable": True, "permission": "ACCOUNTING.RECEIVABLES"},
    "release.accounting.receipts.bulk": {"label": "Bulk actions", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.RECEIVABLES"},
    "release.accounting.receipts.list_print": {"label": "Print receipts list", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.RECEIVABLES"},
    "release.accounting.receipts.print": {"label": "Print one receipt", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.RECEIVABLES"},
    "release.accounting.receipts.process_nsf": {"label": "Process NSF", "entitlement": "nsf_processing", "org_configurable": True, "permission": "ACCOUNTING.RECEIVABLES"},
    "release.accounting.receipts.repeat": {"label": "Repeat prior receipt", "entitlement": "core", "org_configurable": False, "permission": "ACCOUNTING.RECEIVABLES"},
    "release.accounting.tenant_payable": {"label": "Tenant Payable", "entitlement": "core", "org_configurable": True, "permission": "ACCOUNTING.PAYABLES"},
    "release.accounting.vendor_credits": {"label": "Enter Credit", "entitlement": "vendor_credits", "org_configurable": True, "permission": "ACCOUNTING.PAYABLES"},
    "release.accounting.write_checks": {"label": "Write Checks", "entitlement": "check_writing", "org_configurable": True, "permission": "ACCOUNTING.PAYABLES"},
    "release.documents.attachments": {"label": "Universal attachments", "entitlement": "core", "org_configurable": True, "permission": ""},
    "release.maintenance.work_order_to_bill": {"label": "Convert Work Order to Bill", "entitlement": "maintenance", "org_configurable": True, "permission": "ACCOUNTING.PAYABLES"},
    "release.owner_portal.packet_customizer": {"label": "Owner Packet customizer", "entitlement": "owner_portal", "org_configurable": True, "permission": "ACCOUNTING.OWNER_STATEMENTS"},
    "release.owner_statements.email": {"label": "Email statement", "entitlement": "owner_portal", "org_configurable": True, "permission": "ACCOUNTING.OWNER_STATEMENTS"},
    "release.properties": {"label": "Properties list", "entitlement": "core", "org_configurable": False, "permission": "PROPERTIES.ALL"},
    "release.properties.budget": {"label": "Budget tab", "entitlement": "budgeting", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.properties.compliance": {"label": "Compliance tab", "entitlement": "compliance", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.properties.fixed_assets": {"label": "Fixed Assets tab", "entitlement": "fixed_assets", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.properties.groups": {"label": "Property Groups", "entitlement": "property_groups", "org_configurable": True, "permission": "PROPERTIES.GROUPS"},
    "release.properties.keys": {"label": "Keys tracking", "entitlement": "core", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.properties.map": {"label": "Map view", "entitlement": "core", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.properties.non_revenue": {"label": "Non-Revenue tab", "entitlement": "core", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.properties.photo_editor": {"label": "Photo editor", "entitlement": "core", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.properties.rubs": {"label": "RUBs tab", "entitlement": "rubs", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.properties.staff": {"label": "Staff tab", "entitlement": "core", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.properties.statement_settings": {"label": "Statement Settings", "entitlement": "owner_statements", "org_configurable": True, "permission": "PROPERTIES.ALL"},
    "release.reporting.export": {"label": "Export CSV / Excel", "entitlement": "core", "org_configurable": True, "permission": "REPORTING.ALL"},
    "release.settings.accounting": {"label": "Accounting Settings", "entitlement": "core", "org_configurable": True, "permission": "SETTINGS.ACCOUNTING"},
    "release.settings.approvals": {"label": "Approvals", "entitlement": "approvals", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.audit": {"label": "Auditing Center", "entitlement": "audit_center", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.communication": {"label": "Communication", "entitlement": "messaging", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.company": {"label": "Company / Branding", "entitlement": "core", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.currencies": {"label": "Currencies page", "entitlement": "core", "org_configurable": False, "permission": "SETTINGS.CURRENCIES"},
    "release.settings.data": {"label": "Data / Backup / Retention", "entitlement": "core", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.developer": {"label": "Developer / API Keys", "entitlement": "api_access", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.display": {"label": "Display settings page", "entitlement": "core", "org_configurable": False, "permission": "SETTINGS.DISPLAY"},
    "release.settings.documents": {"label": "Documents", "entitlement": "documents", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.features": {"label": "Features", "entitlement": "core", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.leasing": {"label": "Leasing", "entitlement": "leasing", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.maintenance": {"label": "Maintenance", "entitlement": "maintenance", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.owners": {"label": "Owners", "entitlement": "owner_portal", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.permissions": {"label": "Permissions page", "entitlement": "core", "org_configurable": False, "permission": "SETTINGS.PERMISSIONS"},
    "release.settings.property_groups": {"label": "Property Groups", "entitlement": "property_groups", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.risk_tags_affordable": {"label": "Risk / Tags / Affordable", "entitlement": "compliance", "org_configurable": True, "permission": "SETTINGS"},
    "release.settings.security": {"label": "Security", "entitlement": "security_controls", "org_configurable": True, "permission": "SETTINGS"},
    "release.universal.repeat_field": {"label": "CTRL+J repeat field", "entitlement": "core", "org_configurable": True, "permission": ""},
    "release.universal.repeat_form": {"label": "CTRL+K repeat form", "entitlement": "core", "org_configurable": True, "permission": ""},
}
